### ISSUE TITLE
Stratification for user datasets

### ISSUE THREAD

**Issue by jdries** [WorldCereal/ewoc_rdm_api#10] opened 2024-04-17 09:23 UTC

**Comment by santoshkaranam** [comment] 2024-04-22 05:44
This issue is a duplicate of #8

**Comment by kvantricht** [comment] 2024-07-10 09:16
Waiting for the fast API scripts from @cbutsko .

**Comment by cbutsko** [comment] 2024-08-21 08:51
The API call is implemented here https://github.com/WorldCereal/worldcereal-referencedata/blob/main/harmonization/main.py
waiting for testing/deployment from IASA side

**Closed** 2024-08-21 09:03 UTC
