### ISSUE TITLE
Update Instruction to make User dataset public in RDM UI

### ISSUE THREAD

**Issue by jdries** [WorldCereal/ewoc_rdm_api#13] opened 2024-05-02 09:41 UTC

**Comment by jdegerickx** [comment] 2024-07-03 12:29
we would need a web form for the user to complete the necessary additional information required...
Hendrik is working on a list of items to inquire...

**Comment by kvantricht** [comment] 2024-07-10 09:14
Meeting to be organized between IIASA and WENR.

**Comment by boog-wur** [comment] 2024-07-16 14:50
Before organize a meeting I would like to prepare some documents:

- Define protocol how to publish
- Prepare overview how metadata must be organized and completed
- Prepare a Word template with placeholders to support automated generation

**Comment by boog-wur** [comment] 2024-07-16 14:56
I have prepared an overview on how metadata items can be organized and made complete. See https://vitoresearch.sharepoint.com/:x:/r/sites/21717-ccn-world-cereal/Shared%20Documents/Research%20and%20Development/Reference_data/[Metadata-proposal.xlsx](https://vitoresearch.sharepoint.com/:x:/r/sites/21717-ccn-world-cereal/Shared%20Documents/Research%20and%20Development/Reference_data/Metadata-proposal.xlsx?d=w0cf20d2c64214a0685df43c5979b4b83&csf=1&web=1&e=IF1inx)?d=w0cf20d2c64214a0685df43c5979b4b83&csf=1&web=1&e=IF1inx

@santoshkaranam / @jdegerickx : please have a look. See columns F, G and H.

This should be the starting point to create the web form to edit the metadata items either by the data holder / moderator or only be the moderator

**Comment by boog-wur** [comment] 2024-07-16 14:58
One other question for @santoshkaranam : In the RDM UI I see the Title (top part) and the DataSet Name (bottom part). These are different? And where does this come from? The DataSet Name by the data holder during upload? Is then the Title created by the moderator?

**Comment by santoshkaranam** [comment] 2024-07-17 06:59
@boog-wur in the metadata files, these are autogenerated, hence gray cell in Excel sheet. The title at both places is the same.
The title is given at the time of upload. The tile can also be edited later, collectionID cannot be edited

![image](https://github.com/user-attachments/assets/61362c79-eec0-484c-9f0e-5f01c456884b)

**Comment by boog-wur** [comment] 2024-07-17 07:05
@Santosh: you refer to the new phase 2 data sets? For the phase 1 data sets there is a difference between Title and  DataSet Name, right? Anyway, that is no problem, we can keep these differences for the phase 1 data set. Do you agree?

**Comment by santoshkaranam** [comment] 2024-07-17 07:18
So i checked the Metadata from Phase1 - Phase1 website - https://worldcereal-rdm.geo-wiki.org/collections/
![image](https://github.com/user-attachments/assets/7b7fa794-a3d4-443e-a8cc-0be5f14abd43)

The name refers to collectionID and both are the same, so are in phase2 also , yes we can keep them as is.

**Comment by boog-wur** [comment] 2024-07-17 07:30
@santoshkaranam : we have a misunderstanding. I refer to other fields. See attached screen dump. There you so title that differs from a the data set name. 
![image](https://github.com/user-attachments/assets/94780dba-275b-4bf7-9b95-a375409df960)

**Comment by santoshkaranam** [comment] 2024-07-17 07:36
ok @boog-wur  got it, So on the website there is an issue with the heading text, Dataset Name should be actually Description. Ill change it. In Excel, it is correctly marked as description
![image](https://github.com/user-attachments/assets/685000cb-59b9-4593-9c34-bad63667647d)

**Comment by santoshkaranam** [comment] 2024-07-17 07:46
@boog-wur, so the top title is for the harmonized dataset inside the RDM. The bottom "dataset Name" field is the original dataset name, if available. And yes, we can keep both for phase 2 as well. If user knows the original dataset name, user can provide

**Comment by boog-wur** [comment] 2024-07-17 08:14
In Phase 1 we had a name for the original data (OriginalDataSet:NameDataSet::). This is the name the data holder / user will give during upload and is presented in the UI bottom (Dataset Name). In Phase 1 we had several entries for the curated data set:
- CuratedDataSet:ReferenceCuratedDataSet:NameCuratedDataSet: (actually the filename)
- CuratedDataSet::TitleCuratedDataSet: (UI: Top - title)
- CuratedDataSet::DescriptionCuratedDataSet: (UI: Top - description)

In Phase 2 we want to keep it simpler. We have: 
- OriginalDataSet:NameDataSet:: provided by the data holder / user during upload. We could keep it in the UI (Bottom - Dataset Name)
- Keep CuratedDataSet::TitleCuratedDataSet: (UI: Top - title)
- Skip CuratedDataSet::DescriptionCuratedDataSet: (UI: Top - description)

Then the issue is when we ask for the title? It must be short and easy to recognize. Could it be the same as the name provided by the data holder / user during upload. Thus the same as OriginalDataSet:NameDataSet::? And use it for both the UI Top Title and UI Bottom Dataset Name. Then during publishing we can adapt the Title in case it is too long and less attrative for the public.

**Comment by jdegerickx** [comment] 2024-07-17 08:59
I agree trying to keep things simple. Only asking the user to provide a short name (which can then be used to compile the official collectionID) + a short description during dataset upload and then use that one as much as possible.

**Comment by jdegerickx** [comment] 2024-07-17 09:09
@boog-wur, I have reviewed your excel file and provided some comments in columns H/I. Thanks for preparing!

**Comment by boog-wur** [comment] 2024-07-17 10:06
@jdegerickx : thanks, I updated some cells and replied to your comments

**Comment by boog-wur** [comment] 2024-08-12 11:11
Now that the metadata is more or less clear I worked on the protocol on how to publish harmonized data. I wrote a text that can be shown in case the user decides to publish the data (button "share with consortium", perhaps better to call it "share with community").

Before we can publish this text the metadata editor should be ready. See previous discussion. For now we could just show one line that user have to contact the WorldCereal moderator if they want to share.

See this link for the text on the publication pages:
https://vitoresearch.sharepoint.com/:w:/r/sites/21717-ccn-world-cereal/Shared%20Documents/System/RDM/Instructions%20to%20publish%20data.docx?d=wb6dde3b6c44143aca5a1200909176c0b&csf=1&web=1&e=5v8ZTR

Finally I need to create a template with placeholders for the harmonization document

**Comment by boog-wur** [comment] 2024-08-27 08:21
See https://github.com/WorldCereal/worldcereal-referencedata/issues/48

**Comment by jdegerickx** [comment] 2024-12-17 14:05
This has been discussed during today's meeting (VITO + IIASA + WENR) and will be followed-up in more dedicated github issues.

For now we don't allow a user to share data with the public and we need to inform the user on this
--> tracked in #80

**Closed by jdegerickx** 2024-12-17 14:05 UTC
